version: '3.3'

services:

  mssql:
    container_name: DeliveryKing-MSSQL-Server
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"

  redis:
    image: "redis:alpine"
    container_name: DeliveryKing-Redis
    command: --port 6300
    ports:
      - "5100:6300"
    expose:
      - "5100"
    volumes:
      - type: volume
        source: redis-data
        target: /data
    restart: always
  redis-commander:
    container_name: DeliveryKing-Redis-Commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6300
    ports:
      - "8082:8081"
volumes:
  redis-data: {}